include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_put_required_named_parameters_first
    - unnecessary_lambdas
    - prefer_final_in_for_each
    - prefer_final_locals
    - cascade_invocations
    - unnecessary_raw_strings
    - specify_nonobvious_local_variable_types
    - type_annotate_public_apis
    - sort_child_properties_last
    - sized_box_shrink_expand
    - avoid_redundant_argument_values
    - prefer_int_literals
    - avoid_relative_lib_imports
    - unnecessary_breaks
    - unnecessary_await_in_return
    - use_decorated_box
    - no_literal_bool_comparisons
    - use_colored_box
    - use_enums
    - unrelated_type_equality_checks
    - use_build_context_synchronously
    - unnecessary_parenthesis
    - prefer_const_declarations
    - avoid_slow_async_io
    - file_names
    - unnecessary_nullable_for_final_variable_declarations
    - depend_on_referenced_packages
    - join_return_with_assignment
    - avoid_void_async
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - prefer_constructors_over_static_methods
    - avoid_bool_literals_in_conditional_expressions
    - use_if_null_to_convert_nulls_to_bools
    - use_named_constants
    - noop_primitive_operations
    - unnecessary_null_checks
    - prefer_if_elements_to_conditional_expressions
    - cast_nullable_to_non_nullable
    - unnecessary_brace_in_string_interps
    - avoid_multiple_declarations_per_line
    - prefer_spread_collections
    - unnecessary_to_list_in_spreads
    - use_raw_strings
    - use_string_buffers
    - avoid_single_cascade_in_expression_statements
    - unnecessary_const
    - prefer_const_constructors

#    - always_declare_return_types
#    - require_trailing_commas
#    - avoid_unnecessary_containers
#    - avoid_print
#    - use_key_in_widget_constructors
#    - unnecessary_getters_setters
#    - always_put_control_body_on_new_line
#    - avoid_field_initializers_in_const_classes
#    - matching_super_parameters
#    - leading_newlines_in_multiline_strings
#    - unnecessary_underscores
#    - use_to_and_as_if_applicable
#    - no_runtimeType_toString
#    - only_throw_errors
#    - prefer_void_to_null
#    - use_null_aware_elements
#    - prefer_mixin
#    - prefer_null_aware_method_calls
#    - throw_in_finally
#    - use_truncating_division

#    - unawaited_futures
#    - sort_pub_dependencies
#    - prefer_final_parameters
#    - avoid_dynamic_calls
#    - close_sinks
#    - flutter_style_todos
#    - avoid_positional_boolean_parameters
