name: flutter_examples
description: Random flutter examples.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_webview_plugin: ^0.4.0
  geolocator: ^11.0.0
  http: ^1.2.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true